# Generated by Django 3.0.3 on 2020-06-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_embedding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='face_embedding',
        ),
        migrations.AddField(
            model_name='person',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
