# Generated by Django 3.0.8 on 2020-07-25 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_embedding', '0002_auto_20200725_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_event',
            name='attend_time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 25, 14, 52, 7, 665582)),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='face_embedding',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='image_url',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='employee_event',
            unique_together={('event', 'employee')},
        ),
    ]
