# Generated by Django 3.0.3 on 2020-06-16 09:32

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('face_embedding', '0002_auto_20200616_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='face_embedding',
            field=picklefield.fields.PickledObjectField(default=None, editable=False, null=True),
        ),
    ]
