# Generated by Django 3.0.8 on 2020-07-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_embedding', '0002_auto_20200718_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='event', to='face_embedding.Employee'),
        ),
    ]
