# Generated by Django 3.0.3 on 2020-06-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_embedding', '0004_person_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='face_embedding',
            field=models.TextField(null=True),
        ),
    ]
