# Generated by Django 3.0.3 on 2020-06-19 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face_embedding', '0005_auto_20200616_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='face_embedding',
        ),
        migrations.RemoveField(
            model_name='person',
            name='image_url',
        ),
        migrations.AddField(
            model_name='person',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_embedding', models.TextField(null=False)),
                ('image_url', models.TextField(null=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face', 
                null=False,
                to='face_embedding.Person')),
            ],
        ),
    ]
