# Generated by Django 3.0.8 on 2020-07-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_embedding', '0005_auto_20200719_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtemplate',
            name='repeated_every',
            field=models.BigIntegerField(null=True),
        ),
    ]
