# Generated by Django 3.0.8 on 2020-07-19 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face_embedding', '0006_auto_20200719_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceembedding',
            name='created_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='organization',
            field=models.ForeignKey(db_column='organization', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='event_template', to='face_embedding.Organization'),
        ),
    ]
