# Generated by Django 3.0.8 on 2020-07-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_embedding', '0007_auto_20200719_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
